### ISSUE TITLE
Incorrect license (says proprietary but should be GPLv3)

### ISSUE THREAD

**Issue by prurigro** [flathub/io.github.NhekoReborn.Nheko#1]
Link to the license: https://github.com/Nheko-Reborn/nheko/blob/master/COPYING

**Comment by hfiguiere** [comment]
Upstream provided .appdata file says "  <project_license>GPL-3.0-or-later and CC-BY</project_license>" which combined lead to that. Note that usually one doesn't put the data license in there, but that's upstream choice.

**Comment by deepbluev7** [comment]
I guess we should just remove the CC-BY from the appdata then, if it doesn't work with flatpak. I never actually looked at that. :D

**Comment by deepbluev7** [comment]
Where do you actually see the license? It seems correct here: https://flathub.org/apps/details/io.github.NhekoReborn.Nheko

**Comment by hfiguiere** [comment]
GNOME software for example.

The flathub frontend doesn't make judgement on the license, it just display the info.

**Comment by deepbluev7** [comment]
Hm, the Fedora packaging guidelines do use an "and" in their examples too, so I guess I need to do some more research on what actually works with GNOME software. https://docs.fedoraproject.org/en-US/packaging-guidelines/AppData/

**Comment by hfiguiere** [comment]
> I guess we should just remove the CC-BY from the appdata then, if it doesn't work with flatpak. I never actually looked at that. :D

Not sure what the CC-BY relates to, but this is the general opinion:
https://tecnocode.co.uk/2021/07/05/dont-generally-put-cc-by-sa-in-appdata/

**Comment by deepbluev7** [comment]
Should be fixed with our next release, I hope.
