### ISSUE TITLE
Update app id to im.nheko.Nheko

### ISSUE THREAD

**Issue by foresto** [flathub/io.github.NhekoReborn.Nheko#18]
As announced in the [release notes](/Nheko-Reborn/nheko/releases/tag/v0.12.0) and [This Week in Matrix](https://matrix.org/blog/2024/06/14/this-week-in-matrix-2024-06-14/#nheko-website), Nheko's app id has changed from `io.github.NhekoReborn.Nheko` to `im.nheko.Nheko`, effective in version 0.12.0.

The change has already been applied in the [upstream manifest](/Nheko-Reborn/nheko/blob/master/im.nheko.Nheko.yaml). It still needs updating in flathub's build.

**Comment by deepbluev7** [comment]
This had alraedy been work-in-progress at the time... https://github.com/flathub/flathub/pull/5328
